export const menuRoutes: API.MenuRoutesType[] = [
  /**
   * 菜单的配置项，用于动态渲染：
   *  key: 唯一标志
   *  title: 菜单项值（国际化已开启）
   *  path：用于路由跳转
   *  component：组件所在路径，从pages路径下开始
   *  icon：菜单图标
   *  hidden: 是否隐藏该菜单项
   *  routes：子级菜单项
   */
  {
    key: "detail",
    title: "Detail",
    path: "/detail",
    component: "./detail/index",
    hideTabBar: true, // 需要隐藏 TabBar 的页面
    showBack: true,
  },
  {
    key: "home",
    title: "首页",
    path: "/home",
    component: "./home/index",
  },
  {
    key: "event",
    title: "大事件",
    path: "/event",
    component: "./personalCenter/components/EventList",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "event",
    title: "事件记录",
    path: "/event/add",
    component: "./home/components/majorTabs/components/Add",
    hideTabBar: true, // 需要隐藏 TabBar 的页面
    showBack: true,
  },
  {
    key: "baby",
    title: "育儿",
    path: "/baby",
    component: "./baby/index",
  },
  {
    key: "baby/add",
    title: "喂养记录",
    path: "/baby/add",
    hideTabBar: true,
    component: "./baby/feeding/components/Add",
    showBack: true,
  },
  {
    key: "scan",
    title: "扫码",
    path: "/scan",
    component: "./scan/index",
  },
  {
    key: "notice",
    title: "通知",
    path: "/notice",
    component: "./notice/index",
  },
  {
    key: "notice/add",
    title: "创建通知",
    path: "/notice/add",
    component: "./notice/components/Add",
  },
  {
    key: "msg",
    title: "消息",
    path: "/msg",
    component: "./msg/common",
  },
  {
    path: "/msg/like-collect",
    component: "@/pages/msg/LikeCollect",
    title: "赞和收藏",
    hideTabBar: true,
  },
  {
    path: "/msg/chat/:userId",
    component: "@/pages/msg/Chat",
    title: "对话",
    hideTabBar: true,
  },
  {
    path: "/msg/contacts",
    component: "@/pages/msg/contacts",
    title: "联系人",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "notice",
    title: "文章消息",
    path: "/notice/article",
    component: "./personalCenter/components/WwNotice",
    hideTabBar: true,
  },
  {
    key: "mail",
    title: "邮件信息",
    path: "/msg/sendMail",
    component: "./msg/components/SendMail",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "person",
    title: "个人中心",
    path: "/person",
    component: "./personalCenter/index",
  },
  {
    path: "/settings/personalize",
    component: "@/pages/settings/Personalize",
    title: "个性化设置",
    hideTabBar: true,
  },
  {
    key: "bill",
    title: "我的账单",
    path: "/bill",
    component: "./personalCenter/components/WwBillList",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "goal",
    title: "我的目标",
    path: "/goal",
    component: "./personalCenter/components/WwGoal",
    hideTabBar: true,
  },
  {
    key: "voice",
    title: "我的声音",
    path: "/voice",
    component: "./personalCenter/components/WwVoice",
    hideTabBar: true,
  },
  {
    key: "album",
    title: "宝宝相册",
    path: "/baby/album",
    component: "./baby/album/index",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "todo",
    title: "我的待办",
    path: "/todo",
    component: "./personalCenter/components/WwTodo",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "vaccination",
    title: "接种记录",
    path: "/vaccination",
    component: "./personalCenter/components/WwVaccination",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "article",
    title: "文章",
    path: "/article",
    component: "./article/index",
  },
  {
    key: "article-detail",
    title: "文章详情",
    path: "/article/detail/:id",
    component: "./article/components/detail",
    hideTabBar: true,
    showBack: true,
    isDetails: true,
  },
  {
    key: "article-add",
    title: "写文章",
    path: "/article/add",
    component: "./article/components/add",
    hideTabBar: true,
  },
  {
    key: "article-add-setting",
    title: "文章设置",
    path: "/article/addSetting",
    component: "./article/components/addSetting",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "article-collections",
    title: "我的收藏",
    path: "/article/collections",
    component: "./article/collections",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "collect",
    title: "收藏",
    path: "/collect",
    component: "./personalCenter/components/WwCollect",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "tag",
    title: "标签",
    path: "/collect/tag",
    component: "./personalCenter/components/WwCollect/WwTag",
    hideTabBar: true,
  },
  {
    key: "settings",
    title: "设置",
    path: "/settings",
    component: "./settings/index",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "checkIn",
    title: "签到",
    path: "/checkIn",
    component: "./personalCenter/components/WwCheckIn/index",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "checkIn-setting",
    title: "设置签到地点",
    path: "/checkIn/setting",
    component: "./personalCenter/components/WwCheckIn/Map",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "settings/notification",
    title: "通知设置",
    path: "/settings/notification",
    component: "./settings/NotificationSettings",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "settings/change-password",
    title: "修改密码",
    path: "/settings/change-password",
    component: "./settings/ChangePassword",
    hideTabBar: true,
    showBack: true,
  },
  {
    key: "edit-username",
    title: "用户名修改",
    path: "/settings/edit-username",
    component: "./settings/EditUsername",
    hideTabBar: true,
  },
  {
    key: "add-goal",
    title: "添加目标",
    path: "/personalCenter/add-goal",
    component: "./personalCenter/components/WwGoal/AddGoal",
    hideTabBar: true,
    showBack: true,
  },
];
